### ISSUE TITLE
.mat file are not provided

### ISSUE THREAD

**Issue by Juicechen95** [aayushbansal/MarrRevisited#3]
For the ground truth and bestmodel results, there are only .png file provided. But .mat files are needed. What is the format of .mat file?  Can you provide you .mat file or the transforming code?

**Comment by Juicechen95** [comment]
Thanks a lot!!!

**Comment by aayushbansal** [comment]
Try out -- https://www.dropbox.com/s/s85qfjq6xq9n63x/marr-revisited.zip?dl=0
